### ISSUE TITLE
images

### ISSUE THREAD

**Issue by sahilkr37** [akhilsharmaa/WakandaForever-TechFest-3rdPrice#5]
![thumbnail__O6A3337-768x512](https://user-images.githubusercontent.com/111484416/227681712-e7af7ea3-15e4-4513-83e7-9744cef51082.jpg)

**Comment by sahilkr012004** [comment]
![DSC7570-768x512](https://user-images.githubusercontent.com/111484416/227681878-6f2b8002-d2d6-4049-9b74-dcb45235a28f.jpg)


![DSC7710-768x512](https://user-images.githubusercontent.com/111484416/227681886-3a568e1d-c9ef-4ca0-a7ad-523d44fe6bc6.jpg)

**Comment by sahilkr012004** [comment]
![227681646-df60047d-800e-4879-8a23-9ce9cf09cfd9](https://user-images.githubusercontent.com/111484416/227681905-8c24b29a-67a7-4cf9-829b-096d0a330751.jpg)

**Comment by sahilkr012004** [comment]
![ECE-Department11](https://user-images.githubusercontent.com/111484416/227682061-bde095ab-19bf-466b-a11a-2965d982078e.jpg)
![computer-block-768x516](https://user-images.githubusercontent.com/111484416/227682079-f4b19258-2c33-429b-a4a0-53e3fc94a8db.jpg)



![Chem-Deptt -Main-Building](https://user-images.githubusercontent.com/111484416/227682090-a9528130-de07-4501-95a2-00e912e9c146.jpg)

**Comment by sahilkr012004** [comment]
![faculty](https://user-images.githubusercontent.com/111484416/227682361-c872be6f-aa08-4777-b16c-fae2781edafe.jpg)
![60a4dfb468249-bpthumb](https://user-images.githubusercontent.com/111484416/227682366-dce49b42-3c24-4f4a-aa36-0b29749906c9.jpg)
![6062c045b5cc4-bpthumb](https://user-images.githubusercontent.com/111484416/227682371-6346b8fc-a42d-43bc-bda3-804635118e3a.jpg)
![719e51d26ecb86fea85023f58ba2d8a1-bpthumb](https://user-images.githubusercontent.com/111484416/227682377-62e0ccfd-2a4e-4c42-baa9-4c460f6ea495.jpg)
![7e9ec4abdeca51acd46dcdfb5a67d618-
![c46e6a78ccde76011614b8587e70ce82-bpthumb](https://user-images.githubusercontent.com/111484416/227682385-d07767b8-7fde-4f6f-8ab7-3d1e52561768.jpg)

bpthumb](https://user-images.githubusercontent.com/111484416/227682382-63ceec04-86fc-432a-bfa5-cb84ade31859.jpg)



![84aef4ccfbb7c1bd3e0004f32132c6ee-bpthumb](https://user-images.githubusercontent.com/111484416/227682399-f6d0914d-4b59-4523-a733-11877d91f702.jpg)

![29035b4f37845853140f2668dd1f646d-bpthumb](https://user-images.githubusercontent.com/111484416/227682403-fa51724e-d1cc-4d46-b835-a9c31a8cc448.jpg)



![632d45e981533-bpthumb](https://user-images.githubusercontent.com/111484416/227682407-02ddd9bf-1856-4c75-bcb6-61a07b1c7ce6.jpg)
![5f98fdb742a42-bpthumb](https://user-images.githubusercontent.com/111484416/227682410-3bc6767d-4e66-4bcf-89c1-d2068f30d3ba.jpg)

![63234456bd8cd-bpthumb](https://user-images.githubusercontent.com/111484416/227682418-a5d9d101-37f3-48fd-b97c-1767a7583b22.jpg)
![797522a45471b8f3791b2cfe83f8947f-bpthumb](https://user-images.githubusercontent.com/111484416/227682423-0bcbc34f-2a55-4440-bd2f-8d0ad19ead16.jpg)

![Adv -Casting-Lab-e1617101193917](https://user-images.githubusercontent.com/111484416/227682429-cf4fe045-9807-474d-9e68-53d699d377e2.jpg)




![machine-e1617208393467](https://user-images.githubusercontent.com/111484416/227682432-e3a60e32-d82e-4c45-afff-1d0659afd4da.jpg)
![SOM-Lab-e1617100499887](https://user-images.githubusercontent.com/111484416/227682
![IC-Engine-e1617088914609](https://user-images.githubusercontent.com/111484416/227682471-1e8b64d2-2b94-45ce-9214-25c277b56bcc.jpg)
468-052a1858-b6ba-4051-bcee-9942729f2518.jpg)

![1-e1617617093362](https://user-images.githubusercontent.com/111484416/227682462-6759d1b1-d2c8-41db-a16d-516df28cbfe1.png)
![IMG-20210408-WA0009](https://user-images.githubusercontent.com/111484416/227682466-72d91e1d-3d55-4b6b-b077-a4aef52df62f.jpg)

![simulation-and-project-lab-pic](https://user-images.githubusercontent.com/111484416/227682465-fbcb2f7e-9a20-4383-869d-7249635206c3.jpg)



![cad-cam-lab](https://user-imag
![Metrology-Lab-Photo1](https://user-images.githubusercontent.com/111484416/227682457-88d60473-4ba5-4eb2-b787-51f8655c5ba0.jpg)
es.githubusercontent.com/111484416/22
![Fluid-MEchanics-Lab](https://user
![industrial-engineering](https://use
![RAC-LAB-FINAL-PHOTO](https://user-images.githubusercontent.com/111484416/227682456-bec0b57b-f1e9-453c-9326-571a4fdea56f.jpg)
r-images.githubusercontent.com/111484416/227682450-5afe87bb-cc0a-463b-a2b0-6d588647d367.png)
-images.githubusercontent.com/111484416/227682447-cbce329f-df29-4a46-9491-b38cb48b3ff4.png)
7682443-f413cc85-4469-4dfe-b6d0-0da96058ae96.png)

![welding-e1617209179861](https://user-images.githubusercontent.com/111484416/22768
![autofarm](https://user-images.githubusercontent.com/111484416/227682441-07d734c5-e3d4-438f-8ec0-af3e3ebc1dc6.jpg)
2
![additive-manufacturing--e1617104418682](https://user-images.githubusercontent.com/111484416/227682436-8de64ae9-fcf6-431f-9c2e-da0d8108ff86.png)
434-97794278-5440-4d72-bf6f-2acdd9a982c0.png)

**Comment by sahilkr012004** [comment]
![faculty](https://user-images.githubusercontent.com/111484416/227682576-af49aa13-488e-4437-b1bf-baa2b7e03ad0.jpg)
![60a4dfb468249-bpthumb](https://user-images.githubusercontent.com/111484416/227682583-632fc62f-a5a2-4479-908c-a41a1a8900d9.jpg)
![6062c045b5cc4-bpthumb](https://user-images.githubusercontent.com/111484416/227682587-b073830b-b9a4-43ab-b9cb-87f22cb1bbce.jpg)


![719e51d26ecb86fea85023f58ba2d8a1-bpthumb](https://user-images.githubusercontent.com/111484416/227682591-bbb357af-ce97-4ba7-a9c2-b85a3e3433ad.jpg)


![7e9ec4abdeca51acd46dcdfb5a67d618-bpthumb](https://user-images.githubusercontent.com/111484416/227682593-b8b2e3a2-bb7d-4892-88b5-5a0d7ef92f0e.jpg)
![c46e6a78ccde76011614b8587e70ce82-bpthumb](https://user-images.githubusercontent.com/111484416/227682596-250c001d-eabc-4733-857f-c69eaed4e367.jpg)
![84aef4ccfbb7c1bd3e0004f32132c6ee-bpthumb](https://user-images.githubusercontent.com/111484416/227682598-a4a33e4c-85be-4bb0-a7b2-09ee92e64f46.jpg)









![29035b4f37845853140f2668dd1f646d-bpthumb](https://user-images.githubusercontent.com/111484416/227682600-c28cb5c1-8163-485d-b7ea-fed723945151.jpg)
![632d45e981533-bpthumb](https://user-images.githubusercontent.com/111484416/227682606-ecd53776-3c45-4346-aa1c-41ee9a2b49c8.jpg)


![5f98fdb742a42-bpthumb](https://user-images.githubusercontent.com/111484416/227682612-b6f9aedf-c328-459d-9cd0-e1969d39feec.jpg)

![63234456bd8cd-bpthumb](https://user-images.githubusercontent.com/111484416/227682617-cf7ec307-ef5c-421f-915b-a2d2afe862cb.jpg)




![797522a45471b8f3791b2cfe83f8947f-bpthumb](https://user-images.githubusercontent.com/111484416/227682624-046680ee-7ba1-4c44-b6fc-711c6c371504.jpg)
![Adv -Casting-Lab-e1617101193917](https://user-images.githubusercontent.com/111484416/227682629-d296eddb-8da3-4e11-b2b9-deb24f1c8157.jpg)



![machine-e1617208393467](https://user-images.githubusercontent.com/111484416/227682633-1595c8b2-df86-459e-a58a-d3c0d991105f.jpg)
![welding-e1617209179861](https://user-images.githubusercontent.com/111484416/227682638-191a0f3f-e849-471c-9fbf-f01dadf9a13f.png)



![additive-manufacturing--e1617104418682](https://user-images.githubusercontent.com/111484416/227682641-754791c0-375e-43a4-90aa-f78cf7e7208e.png)

![autofarm](https://user-images.githubusercontent.com/111484416/227682645-9fb8b571-7c01-468b-bcd5-04358a532b8b.jpg)



![cad-cam-lab](https://user-images.githubusercontent.com/111484416/227682649-0b578933-34b8-4b2a-bcfe-7091eeeaf138.png)

**Comment by sahilkr012004** [comment]
![Fluid-MEchanics-Lab](https://user-images.githubusercontent.com/111484416/227682702-2792c079-8de8-4ee0-8cd5-07d1dceb216f.png)
![industrial-engineering](https://user-images.githubusercontent.com/111484416/227682703-872bed09-3237-4ee7-af4e-7c81a57e1e00.png)



![RAC-LAB-FINAL-PHOTO](https://user-images.githubusercontent.com/111484416/227682705-311f70aa-e2e8-408b-9272-db4c62ff0f01.jpg)


![Metrology-Lab-Photo1](https://user-images.githubusercontent.com/111484416/227682708-ca4f5d9c-de56-42f4-838c-a21cf9dc5087.jpg)


![1-e1617617093362](https://user-images.githubusercontent.com/111484416/227682725-06adbeba-8051-4e68-b1f1-f7abdb6347ac.png)



![simulation-and-project-lab-pic](https://user-images.githubusercontent.com/111484416/227682731-cbfc87f8-620a-4852-b8cb-dd4b339bb5db.jpg)

![IMG-20210408-WA0009](https://user-images.githubusercontent.com/111484416/227682739-1218c748-1f5f-4e45-93c3-3372eae0a76a.jpg)

![SOM-Lab-e1617100499887](https://user-images.githubusercontent.com/111484416/227682743-286cc0a5-16df-44eb-8023-04e02b834698.jpg)
![IC-Engine-e1617088914609](https://user-images.githubusercontent.com/111484416/227682745-2339df7e-a911-4c92-ba4f-d6160d259e69.jpg)

![faculty](https://user-images.githubusercontent.com/111484416/227682747-ad5f611c-7c30-42db-bb73-55b3e1a7e941.jpg)

**Comment by sahilkr012004** [comment]
![science-block1](https://user-images.githubusercontent.com/111484416/227689366-b884df20-dad6-4890-9aab-d4d82dc458c4.jpg)


![IMG-5312-768x576](https://user-images.githubusercontent.com/111484416/227689372-8a731eb3-914e-4d95-8b02-a38cf96462f3.jpg)

**Comment by sahilkr012004** [comment]
![DSC_0049-768x516](https://user-images.githubusercontent.com/111484416/227691001-5b220dea-6b27-41ea-a29b-f54f29dc8db6.jpg)
